package com.hyoretsu.checkers;

import java.awt.Color;
import javax.swing.JPanel;

/** GUI of the game board */
public class BoardGUI extends JPanel {
 private GameWindow window;
 private SquareGUI[][] squares;

 /** Creates new form Board */
 public BoardGUI() {
 }

 public BoardGUI(GameWindow window) {
  this.window = window;
  initComponents();
  createSquares();
 }

 /** Fills the board with 64 squares */
 private void createSquares() {
  squares = new SquareGUI[8][8];
  // Up-down
  for (int y = 7; y >= 0; y--) {
   // Left-right
   for (int x = 0; x < 8; x++) {
    Color color = defineColor(x, y);
    SquareGUI square = new SquareGUI(x, y, color, this);
    squares[x][y] = square;
    add(square);
   }
  }
 }

 private Color defineColor(int x, int y) {
  if (x % 2 == 0) { // Even line
   if (y % 2 == 0) { // Even column
    return SquareGUI.COLOR_DARK;
   } else { // Odd column
    return SquareGUI.COLOR_LIGHT;
   }
  } else { // Odd line
   if (y % 2 == 0) { // Even column
    return SquareGUI.COLOR_LIGHT;
   } else { // Odd column
    return SquareGUI.COLOR_DARK;
   }
  }
 }

 public GameWindow getWindow() {
  return window;
 }

 public void update(Game game) {
  for (int x = 0; x < 8; x++) {
   for (int y = 0; y < 8; y++) {
    SquareGUI squareGUI = squares[x][y];

    Board board = game.getBoard();
    Square square = board.getSquare(x, y);
    if (square.hasPiece()) {
     Piece piece = square.getPiece();

     switch (piece.getType()) {
      case Piece.WHITE:
       squareGUI.drawWhitePiece();
       break;
      case Piece.WHITE_KING:
       squareGUI.drawWhiteKing();
       break;
      case Piece.RED:
       squareGUI.drawRedPiece();
       break;
      case Piece.RED_KING:
       squareGUI.drawRedKing();
       break;
     }
    } else {
     squareGUI.removePiece();
    }
   }
  }
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated
 // Code">//GEN-BEGIN:initComponents
 private void initComponents() {
  setLayout(new java.awt.GridLayout(8, 8));
 }// </editor-fold>//GEN-END:initComponents

 // Variables declaration - do not modify//GEN-BEGIN:variables
 // End of variables declaration//GEN-END:variables
}
