package com.hyoretsu.checkers.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.hyoretsu.checkers.Game;

/** Main window of the game */
public class Window extends JFrame {
 private Game game;
 private boolean firstClick = true;
 private SquareGUI originSquare = null;
 private SquareGUI destinationSquare = null;

 public Window() {
  this.initComponents();
  this.newGame();

  // Add action listener to "new" menu
  this.newMenu.addActionListener(new ActionListener() {
   public void actionPerformed(ActionEvent e) {
    newGame();
   }
  });

  // Add action listener to "exit" menu
  this.exitMenu.addActionListener(new ActionListener() {
   @Override
   public void actionPerformed(ActionEvent e) {
    dispose();
   }
  });

  super.setLocationRelativeTo(null);
  super.setVisible(true);
  super.pack();
 }

 /** Creates a new game and updates the board GUI. */
 private void newGame() {
  if (!this.firstClick) {
   this.firstClick = true;
   this.originSquare.deselect();
  }
  this.game = new Game();
  this.update();
 }

 /**
  * Responds to clicks in the board
  *
  * @param clickedSquare Square the player just clicked.
  */
 public void respond(SquareGUI clickedSquare) {
  if (this.firstClick) {
   if (clickedSquare.hasPiece()) {
    this.originSquare = clickedSquare;
    this.originSquare.select();
    this.firstClick = false;
   } else { // Didn't click on a valid square
    JOptionPane.showMessageDialog(this, "Click on a piece.");
   }
  } else {
   this.destinationSquare = clickedSquare;
   this.game.movePiece(this.originSquare.getPosX(), this.originSquare.getPosY(), this.destinationSquare.getPosX(),
     this.destinationSquare.getPosY());
   this.originSquare.deselect();
   this.firstClick = true;
   this.update();
  }
 }

 private void update() {
  this.boardGUI.update(this.game);
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated
 // Code">//GEN-BEGIN:initComponents
 private void initComponents() {
  this.linesPanel = new javax.swing.JPanel();
  this.jLabel3 = new javax.swing.JLabel();
  this.jLabel4 = new javax.swing.JLabel();
  this.jLabel5 = new javax.swing.JLabel();
  this.jLabel6 = new javax.swing.JLabel();
  this.jLabel7 = new javax.swing.JLabel();
  this.jLabel8 = new javax.swing.JLabel();
  this.jLabel2 = new javax.swing.JLabel();
  this.jLabel1 = new javax.swing.JLabel();
  this.columnsPanel = new javax.swing.JPanel();
  this.lbl_a = new javax.swing.JLabel();
  this.lbl_b = new javax.swing.JLabel();
  this.lbl_c = new javax.swing.JLabel();
  this.lbl_d = new javax.swing.JLabel();
  this.lbl_e = new javax.swing.JLabel();
  this.lbl_f = new javax.swing.JLabel();
  this.lbl_g = new javax.swing.JLabel();
  this.lbl_h = new javax.swing.JLabel();
  this.boardGUI = new BoardGUI(this);
  this.jMenuBar1 = new javax.swing.JMenuBar();
  this.archiveMenu = new javax.swing.JMenu();
  this.newMenu = new javax.swing.JMenuItem();
  this.jSeparator1 = new javax.swing.JPopupMenu.Separator();
  this.exitMenu = new javax.swing.JMenuItem();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  this.linesPanel.setLayout(new java.awt.GridLayout(8, 1));

  this.jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
  this.jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.jLabel3.setText("7");
  this.linesPanel.add(this.jLabel3);

  this.jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
  this.jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.jLabel4.setText("6");
  this.linesPanel.add(this.jLabel4);

  this.jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
  this.jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.jLabel5.setText("5");
  this.linesPanel.add(this.jLabel5);

  this.jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
  this.jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.jLabel6.setText("4");
  this.linesPanel.add(this.jLabel6);

  this.jLabel7.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
  this.jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.jLabel7.setText("3");
  this.linesPanel.add(this.jLabel7);

  this.jLabel8.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
  this.jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.jLabel8.setText("2");
  this.linesPanel.add(this.jLabel8);

  this.jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
  this.jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.jLabel2.setText("1");
  this.linesPanel.add(this.jLabel2);

  this.jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
  this.jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.jLabel1.setText("0");
  this.linesPanel.add(this.jLabel1);

  this.columnsPanel.setLayout(new java.awt.GridLayout(1, 8));

  this.lbl_a.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
  this.lbl_a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.lbl_a.setText("0");
  this.columnsPanel.add(this.lbl_a);

  this.lbl_b.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
  this.lbl_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.lbl_b.setText("1");
  this.columnsPanel.add(this.lbl_b);

  this.lbl_c.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
  this.lbl_c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.lbl_c.setText("2");
  this.columnsPanel.add(this.lbl_c);

  this.lbl_d.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
  this.lbl_d.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.lbl_d.setText("3");
  this.columnsPanel.add(this.lbl_d);

  this.lbl_e.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
  this.lbl_e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.lbl_e.setText("4");
  this.columnsPanel.add(this.lbl_e);

  this.lbl_f.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
  this.lbl_f.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.lbl_f.setText("5");
  this.columnsPanel.add(this.lbl_f);

  this.lbl_g.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
  this.lbl_g.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.lbl_g.setText("6");
  this.columnsPanel.add(this.lbl_g);

  this.lbl_h.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
  this.lbl_h.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  this.lbl_h.setText("7");
  this.columnsPanel.add(this.lbl_h);

  this.archiveMenu.setText("Jogo");

  this.newMenu.setAccelerator(
    javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
  this.newMenu.setText("Novo");
  this.archiveMenu.add(this.newMenu);
  this.archiveMenu.add(this.jSeparator1);

  this.exitMenu.setAccelerator(
    javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
  this.exitMenu.setText("Sair");
  this.archiveMenu.add(this.exitMenu);

  this.jMenuBar1.add(this.archiveMenu);

  setJMenuBar(this.jMenuBar1);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup().addContainerGap()
      .addComponent(this.linesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
        .addComponent(this.columnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE).addComponent(
          this.boardGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
  layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup().addGap(10, 10, 10)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(this.linesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 576,
          javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(this.boardGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE))
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(this.columnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
      .addContainerGap()));

  pack();
 }// </editor-fold>//GEN-END:initComponents

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JLabel jLabel6;
 private javax.swing.JLabel jLabel7;
 private javax.swing.JLabel jLabel8;
 private javax.swing.JMenuBar jMenuBar1;
 private javax.swing.JPopupMenu.Separator jSeparator1;
 private javax.swing.JLabel lbl_a;
 private javax.swing.JLabel lbl_b;
 private javax.swing.JLabel lbl_c;
 private javax.swing.JLabel lbl_d;
 private javax.swing.JLabel lbl_e;
 private javax.swing.JLabel lbl_f;
 private javax.swing.JLabel lbl_g;
 private javax.swing.JLabel lbl_h;
 private javax.swing.JMenu archiveMenu;
 private javax.swing.JMenuItem newMenu;
 private javax.swing.JMenuItem exitMenu;
 private javax.swing.JPanel columnsPanel;
 private javax.swing.JPanel linesPanel;
 private BoardGUI boardGUI;
 // End of variables declaration//GEN-END:variables
}
